name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate linter with phpcs.phar
      run: |
        wget -O phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        chmod +x ./phpcs
        ./phpcs --standard=PSR12 ./
        
  deploy:
    name: Deploy Site
    
    runs-on: ubuntu-latest
    
    needs: [linter]
    
    steps:
    - uses: actions/checkout@v3

    #- name: scp-deployer
    
      # You may pin to the exact commit or the version.
      # uses: siva1024/scp-deployer@595af961c23bfad4cc7c1bcdfe9b57fb840e7cb9
      #run: |
        #scp -i ${{secrets.KEY}} --exclude='*.key' ./ admin@ec2-13-37-249-193.eu-west-3.compute.amazonaws.com:/app
    
    - name: deploy-via-scp
      # You may pin to the exact commit or the version.
      # uses: horochx/deploy-via-scp@c82b42f002701aeca107ef7cf6ea4efe6788141e
      uses: horochx/deploy-via-scp@1.1.0
      with:
        # Local file path
        local: ./
        # Remote file path
        remote: /app
        # Remote server address
        host: ec2-13-37-249-193.eu-west-3.compute.amazonaws.com
        # Remote server user
        user: admin
        # Remote server private key
        key: ${{secrets.key}}

